name: Advection_Diffusion
channels:
  - conda-forge
  - defaults
dependencies:
  - pytest
  - ipython
  - scipy
  - matplotlib
  - jupyterlab
  - python
  - numpy
  - pip
  - git
  - ffmpeg
  - netcdf4
  - bottleneck
  - xarray
  - dask
  - numba
  - holoviews
  - bokeh
  - pillow
  - zarr
  - xrft
  - hvplot
  - datashader
